echo ""
echo ""
echo "     _                         _"
echo "    |_|                       |_|"
echo "    | |         /^^^\         | |"
echo '   _| |_      (| "o" |)      _| |_'
echo " _| | | | _    (_---_)    _ | | | |_ "
echo "| | | | |' |    _| |_    | '| | | | |"
echo "\          /   /     \   \          /"
echo " \        /  / /(. .)\ \  \        /"
echo "   \    /  / /  | . |  \ \  \    /"
echo "     \  \/ /    ||Y||    \ \/  /"
echo "       \_/      || ||      \_/"
echo "                () ()"
echo "                || ||"
echo "               ooO Ooo"
echo ""